### ISSUE TITLE
Aggiungere informazioni su come inviare le email all'omonimo comando

### ISSUE THREAD

**Issue by 7lb** [develersrl/tinabot#10]
Il comando `email` si limita a formattare l'ordine in modo adatto ad essere inviato tramite email, ma non esegue l'invio automatico immagino anche per questioni di eventuale spam (anche involontario).

Però potrebbe essere utile cambiare leggermente il testo in modo da indicare, oltre al subject e body della mail, anche i recipient che, al momento dell'apertura di questa issue, sono `info@tuttobene-bar.it` e `sara@tuttobene-bar.it`

**Comment by rasky** [comment]
Se poi generasse anche un link cliccabile `mailto:` con tutto il corpo della email dentro... :)
https://yoast.com/dev-blog/guide-mailto-links/

**Comment by plorefice** [comment]
@tommyblue direi che questa si può chiudere
