### ISSUE TITLE
Gestione del develunch

### ISSUE THREAD

**Issue by batt** [develersrl/tinabot#5]
Che ne direste se implementassi in tinabot anche la gestione del Develunch? Pensavo semplicemente al fatto che potrebbe essere lei a inviare i reminder giusti e, in caso di develunch, oltre a non prendere ordinazioni lo ricordasse in chat.
  
Per settare un develunch si potrebbe aggiungere un comando "develunch" che prende una data, lei controlla se è un venerdì e automaticamente si schedula i develunch ogni 2 settimane a partire da quella. Così in caso di salto sappiamo come riprogrammarla.

Che ne dite? Pensate che sia una feature utile?

**Comment by Svalorzen** [comment]
Si decisamente utile. Mi immaginerei più che uno chiama develunch per marcare la settimana corrente come di develunch e poi il venerdì di quella settimana più ogni due da i vari warning.

L'unica cosa è che, se non mi ricordo male, tinabot non è sempre sveglia. Nel particolare, dorme sempre a meno che qualcuno non la menzioni (per esempio per settare il menu del giorno) e rimane sveglia per un tot di tempo dopo. Questo è per rimanere nei limiti free di heroku - @tommyblue ne sa più di me.

Per cui succede che nel momento in cui il bot dovrebbe dare il reminder non è acceso e quindi è stato tutto inutile.. Forse si riesce a fare il giovedì che da il warning "domani è develunch!" però.

**Comment by batt** [comment]
Buona idea quello di marcare la settimana invece della data.

Per quanto riguarda l'essere sempre sveglia, tinabot dovrebbe usare una specie di keelalive, o almeno io ho fatto così con il nostro bot embedded (fernandello). Per esempio io l'ho configurato per mandare notifiche in chat a orari programmati ed è da diverse settimane che funziona regolarmente. Il keepalive su heroku fa in modo che il bot sia attivo per 18 ore al giorno (che è il massimo per il piano gratis), con orario di avvio programmmabile.

Se non ci sono altre obiezioni allora magari faccio un primo giro di implementazione e sottopongo una pull request. Ok?

**Comment by tommyblue** [comment]
si, è come dice @batt 
in pratica dovrebbe "dormire" solo la notte (non ricordo esattamente le ore che ho impostato)

**Comment by batt** [comment]
Ok, ho fatto una prima implementazione... però siccome sono disadatto, ho fatto un po' di casino. 

Prima di fare una pull request  per questa feature (https://github.com/batt/tinabot/commit/72d90eda05cb754a6eac4a66982008292e19589b) bisognerebbe mergiare l'altra (la #4)  , fatemi sapere se va bene o se devo fare altro!

**Comment by batt** [comment]
Fatta PR #6
